### ISSUE TITLE
Fix GrowthParams and PrivateSpace objects for not None in models

### ISSUE THREAD

**Issue by sneharai4** [HewlettPackard/hpe3par_python_sdk#23]
Currently, class GrowthParams and PrivateSpace objects do not get initialized when they are not None. This needs to be corrected in models.py like below. 

class GrowthParams(object):

    def __init__(self, object_hash):
        if object_hash is None:
            return

Please check the same in other places.

**Comment by ansarars** [comment]
Raised PR https://github.com/HewlettPackard/hpe3par_python_sdk/pull/24 for this issue

**Comment by sneharai4** [comment]
Fix already merged in master.
